openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: 16|weLnjWanw4mLTdFqNIK52vC2gwtDyANxvAxDvNSv
                  is_company: true
                properties:
                  token:
                    type: string
                    example: 16|weLnjWanw4mLTdFqNIK52vC2gwtDyANxvAxDvNSv
                  is_company:
                    type: boolean
                    example: true
      tags:
        - Authentication
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: djasoijdsaio.
                  example: test@test.com
                password:
                  type: string
                  description: djasoijdsaio.
                  example: password
      security: []
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: 17|oTLLWAaoNkxYdbCu3ESWaZgxotpqZFxU3G51nWBT
                properties:
                  token:
                    type: string
                    example: 17|oTLLWAaoNkxYdbCu3ESWaZgxotpqZFxU3G51nWBT
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: et
                image:
                  type: string
                  format: binary
                  description: 'Must be an image.'
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: gkonopelski@example.com
                password:
                  type: string
                  description: djasoijdsaio.
                  example: password
                type:
                  type: string
                  description: 'Must be one of <code>instute</code> or <code>company</code>.'
                  example: instute
                category_ids:
                  type: array
                  description: djasoijdsaio.
                  example:
                    - 1
                    - 2
                    - 3
                  items:
                    type: string
                created_in:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-09-28T11:43:48'
                address:
                  type: string
                  description: ''
                  example: dicta
                city:
                  type: string
                  description: ''
                  example: dolorem
                password_confirmation:
                  type: string
                  description: djasoijdsaio.
                  example: password
              required:
                - name
                - image
                - email
                - type
                - created_in
                - address
                - city
      security: []
  /api/profile:
    get:
      summary: ''
      operationId: getApiProfile
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  user:
                    id: 46
                    name: 'Bernice Dickinson PhD'
                    image: 'http://localhost:8000/images/https://via.placeholder.com/640x480.png/004488?text=impedit'
                    email: purdy.meghan@example.org
                    email_verified_at: '2023-09-28T10:07:43.000000Z'
                    created_at: '2023-09-28T10:07:43.000000Z'
                    updated_at: '2023-09-28T10:07:43.000000Z'
                    company: null
                  is_company: false
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 46
                      name:
                        type: string
                        example: 'Bernice Dickinson PhD'
                      image:
                        type: string
                        example: 'http://localhost:8000/images/https://via.placeholder.com/640x480.png/004488?text=impedit'
                      email:
                        type: string
                        example: purdy.meghan@example.org
                      email_verified_at:
                        type: string
                        example: '2023-09-28T10:07:43.000000Z'
                      created_at:
                        type: string
                        example: '2023-09-28T10:07:43.000000Z'
                      updated_at:
                        type: string
                        example: '2023-09-28T10:07:43.000000Z'
                      company:
                        type: string
                        example: null
                  is_company:
                    type: boolean
                    example: false
      tags:
        - Authentication
  /api/profile/company:
    get:
      summary: ''
      operationId: getApiProfileCompany
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 30
                  address: nemo
                  city: reiciendis
                  user_id: 46
                  created_in: '2023-09-28T00:00:00.000000Z'
                properties:
                  id:
                    type: integer
                    example: 30
                  address:
                    type: string
                    example: nemo
                  city:
                    type: string
                    example: reiciendis
                  user_id:
                    type: integer
                    example: 46
                  created_in:
                    type: string
                    example: '2023-09-28T00:00:00.000000Z'
      tags:
        - Authentication
  /api/profile/institution:
    get:
      summary: ''
      operationId: getApiProfileInstitution
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 30
                  address: nemo
                  city: reiciendis
                  user_id: 46
                  created_in: '2023-09-28T00:00:00.000000Z'
                properties:
                  id:
                    type: integer
                    example: 30
                  address:
                    type: string
                    example: nemo
                  city:
                    type: string
                    example: reiciendis
                  user_id:
                    type: integer
                    example: 46
                  created_in:
                    type: string
                    example: '2023-09-28T00:00:00.000000Z'
      tags:
        - Authentication
  /api/category:
    get:
      summary: 'Handle the incoming request.'
      operationId: handleTheIncomingRequest
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: Electronics
                  -
                    id: 2
                    name: 'Home & Kitchen'
                  -
                    id: 3
                    name: 'Health & Beauty'
                  -
                    id: 4
                    name: Fashion
                  -
                    id: 5
                    name: 'Sports & Outdoors'
                  -
                    id: 6
                    name: 'Toys & Games'
                  -
                    id: 7
                    name: Books
                  -
                    id: 8
                    name: 'Pet Supplies'
                  -
                    id: 9
                    name: 'Office Supplies'
                  -
                    id: 10
                    name: Jewelry
                  -
                    id: 11
                    name: Automotive
                  -
                    id: 12
                    name: Grocery
                  -
                    id: 13
                    name: 'Movies & TV Shows'
                  -
                    id: 14
                    name: Music
                  -
                    id: 15
                    name: 'Industrial & Scientific'
                  -
                    id: 16
                    name: 'Arts & Crafts'
                  -
                    id: 17
                    name: Baby
                  -
                    id: 18
                    name: 'Tools & Home Improvement'
                  -
                    id: 19
                    name: 'Luggage & Travel Gear'
                  -
                    id: 20
                    name: 'Video Games'
                  -
                    id: 21
                    name: Handmade
                  -
                    id: 22
                    name: 'Collectibles & Fine Art'
                  -
                    id: 23
                    name: 'Digital Products'
                  -
                    id: 24
                    name: 'Gift Cards'
                  -
                    id: 25
                    name: Appliances
                  -
                    id: 26
                    name: 'Audio & Video'
                  -
                    id: 27
                    name: 'Bags & Backpacks'
                  -
                    id: 28
                    name: 'Bath & Body'
                  -
                    id: 29
                    name: 'Bedding & Linens'
                  -
                    id: 30
                    name: Beverages
                  -
                    id: 31
                    name: 'Camping & Hiking'
                  -
                    id: 32
                    name: 'Cameras & Photography'
                  -
                    id: 33
                    name: 'Car Parts & Accessories'
                  -
                    id: 34
                    name: 'Cleaning Supplies'
                  -
                    id: 35
                    name: Collectibles
                  -
                    id: 36
                    name: 'Computer Components'
                  -
                    id: 37
                    name: 'Cookware & Bakeware'
                  -
                    id: 38
                    name: 'Costumes & Accessories'
                  -
                    id: 39
                    name: 'Craft Supplies'
                  -
                    id: 40
                    name: 'Dental Care'
                  -
                    id: 41
                    name: 'Desk Accessories'
                  -
                    id: 42
                    name: 'Diet & Nutrition'
                  -
                    id: 43
                    name: 'Dinnerware & Serveware'
                  -
                    id: 44
                    name: 'DVDs & Blu-ray'
                  -
                    id: 45
                    name: 'Education & Teaching'
                  -
                    id: 46
                    name: 'Event & Party Supplies'
                  -
                    id: 47
                    name: Eyewear
                  -
                    id: 48
                    name: Furniture
                  -
                    id: 49
                    name: 'Gardening & Lawn Care'
                  -
                    id: 50
                    name: 'Hair Care'
                  -
                    id: 51
                    name: 'Handbags & Wallets'
                  -
                    id: 52
                    name: Hardware
                  -
                    id: 53
                    name: 'Headphones & Earbuds'
                  -
                    id: 54
                    name: 'Home Decor'
                  -
                    id: 55
                    name: 'Home Improvement'
                  -
                    id: 56
                    name: 'Home Storage & Organization'
                  -
                    id: 57
                    name: Instruments
                  -
                    id: 58
                    name: 'Jackets & Coats'
                  -
                    id: 59
                    name: "Kids' Clothing"
                  -
                    id: 60
                    name: 'Kitchen & Dining'
                  -
                    id: 61
                    name: 'Laundry Supplies'
                  -
                    id: 62
                    name: 'Lighting & Ceiling Fans'
                  -
                    id: 63
                    name: 'Makeup & Beauty Tools'
                  -
                    id: 64
                    name: 'Medical Supplies & Equipment'
                  -
                    id: 65
                    name: "Men's Clothing"
                  -
                    id: 66
                    name: 'Musical Instruments'
                  -
                    id: 67
                    name: 'Networking & Wireless'
                  -
                    id: 68
                    name: 'Novelty & Gag Toys'
                  -
                    id: 69
                    name: 'Outdoor Decor'
                  -
                    id: 70
                    name: 'Outdoor Power Tools'
                  -
                    id: 71
                    name: 'Painting, Drawing & Art Supplies'
                  -
                    id: 72
                    name: 'Patio Furniture & Accessories'
                  -
                    id: 73
                    name: 'Personal Care'
                  -
                    id: 74
                    name: 'Personal Protective Equipment'
                  -
                    id: 75
                    name: 'Pest Control'
                  -
                    id: 76
                    name: 'Plant-Based Foods'
                  -
                    id: 77
                    name: Plumbing
                  -
                    id: 78
                    name: 'Portable Audio & Speakers'
                  -
                    id: 79
                    name: 'Printers & Ink'
                  -
                    id: 80
                    name: 'Safety & Security'
                  -
                    id: 81
                    name: 'School & Office Supplies'
                  -
                    id: 82
                    name: 'Shaving & Hair Removal'
                  -
                    id: 83
                    name: Shoes
                  -
                    id: 84
                    name: 'Skin Care'
                  -
                    id: 85
                    name: 'Smart Home'
                  -
                    id: 86
                    name: 'Smartphones & Accessories'
                  -
                    id: 87
                    name: Snacks
                  -
                    id: 88
                    name: Software
                  -
                    id: 89
                    name: 'Storage & Organization'
                  -
                    id: 90
                    name: Sunglasses
                  -
                    id: 91
                    name: 'Tablets & Accessories'
                  -
                    id: 92
                    name: 'Tea & Coffee'
                  -
                    id: 93
                    name: Televisions
                  -
                    id: 94
                    name: 'Tires & Wheels'
                  -
                    id: 95
                    name: 'Tools & Equipment'
                  -
                    id: 96
                    name: 'Toys & Collectibles'
                  -
                    id: 97
                    name: 'Travel Accessories'
                  -
                    id: 98
                    name: 'Underwear & Socks'
                  -
                    id: 99
                    name: 'Vacuums & Floor Care'
                  -
                    id: 100
                    name: Vegetables
                  -
                    id: 101
                    name: 'Video Projectors'
                  -
                    id: 102
                    name: Watches
                  -
                    id: 103
                    name: 'Water Bottles'
                  -
                    id: 104
                    name: 'Wine & Spirits'
                  -
                    id: 105
                    name: "Women's Clothing"
                  -
                    id: 106
                    name: 'Workout Clothing'
                  -
                    id: 107
                    name: 'Yoga & Fitness'
                  -
                    id: 108
                    name: 'Zipper Bags'
      tags:
        - Category
      security: []
  /api/offer:
    get:
      summary: ''
      operationId: getApiOffer
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 10
                      trender_name: 'Reprehenderit est esse et.'
                      for: 'Mr. Damon Lockman'
                      work_on_it: '2023-09-17T08:12:58.000000Z'
                      work_ended_it: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 10
                        trender_name: 'Reprehenderit est esse et.'
                        for: 'Mr. Damon Lockman'
                        work_on_it: '2023-09-17T08:12:58.000000Z'
                        work_ended_it: null
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 10
                        trender_name:
                          type: string
                          example: 'Reprehenderit est esse et.'
                        for:
                          type: string
                          example: 'Mr. Damon Lockman'
                        work_on_it:
                          type: string
                          example: '2023-09-17T08:12:58.000000Z'
                        work_ended_it:
                          type: string
                          example: null
      tags:
        - Offer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: 'Must be one of <code>ended</code> or <code>draft</code>.'
                  example: ended
              required:
                - type
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Offer
      security: []
  '/api/offer/{id}':
    get:
      summary: ''
      operationId: getApiOfferId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 10
                    trender_name: 'Reprehenderit est esse et.'
                    for: 'Mr. Damon Lockman'
                    work_on_it: '2023-09-17T08:12:58.000000Z'
                    work_ended_it: null
                    offer_details:
                      -
                        id: 5
                        offer_id: 10
                        tender_detail_id: 10
                        answer: quo
                        created_at: '2023-09-17T08:12:58.000000Z'
                        updated_at: '2023-09-17T08:12:58.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 10
                      trender_name:
                        type: string
                        example: 'Reprehenderit est esse et.'
                      for:
                        type: string
                        example: 'Mr. Damon Lockman'
                      work_on_it:
                        type: string
                        example: '2023-09-17T08:12:58.000000Z'
                      work_ended_it:
                        type: string
                        example: null
                      offer_details:
                        type: array
                        example:
                          -
                            id: 5
                            offer_id: 10
                            tender_detail_id: 10
                            answer: quo
                            created_at: '2023-09-17T08:12:58.000000Z'
                            updated_at: '2023-09-17T08:12:58.000000Z'
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 5
                            offer_id:
                              type: integer
                              example: 10
                            tender_detail_id:
                              type: integer
                              example: 10
                            answer:
                              type: string
                              example: quo
                            created_at:
                              type: string
                              example: '2023-09-17T08:12:58.000000Z'
                            updated_at:
                              type: string
                              example: '2023-09-17T08:12:58.000000Z'
      tags:
        - Offer
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Offer
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Offer
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the offer.'
        example: 1
        required: true
        schema:
          type: integer
  /api/trender:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters:
        -
          in: query
          name: q
          description: ''
          example: molestias
          required: false
          schema:
            type: string
            description: ''
            example: molestias
        -
          in: query
          name: category_ids
          description: ''
          example: []
          required: false
          schema:
            type: object
            description: ''
            example: []
            properties: []
        -
          in: query
          name: cities
          description: ''
          example: []
          required: false
          schema:
            type: object
            description: ''
            example: []
            properties: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 2
                    title: 'Veritatis corporis ut unde.'
                    description: 'Officiis maiores deserunt voluptatum. Est rerum qui et ratione consequatur. Autem id quod ipsa aut alias est id. Rerum doloribus aliquid voluptatem. Necessitatibus aliquid adipisci velit eaque.'
                    ended_at: null
                    institution_id: 7
                    institution_name: 'Abbigail Brakus III'
                  -
                    id: 4
                    title: 'Fugiat qui vitae.'
                    description: 'Officiis accusantium accusantium corporis dicta voluptatem voluptatem. Consequatur perspiciatis enim accusantium ipsum.'
                    ended_at: null
                    institution_id: 9
                    institution_name: 'Odessa Hyatt'
                  -
                    id: 10
                    title: 'Architecto blanditiis corporis eius voluptas dolorem.'
                    description: 'Sunt sapiente aut et eos ipsam laborum. Eaque eum excepturi ea voluptatem et adipisci id nihil. Quis error illo voluptatem sit. Aut eum impedit et provident ipsam aspernatur.'
                    ended_at: null
                    institution_id: 15
                    institution_name: 'Alisha Kuphal V'
                  -
                    id: 12
                    title: 'Qui rerum libero quo et.'
                    description: 'Mollitia quaerat quo in in repellendus corporis corrupti. Laboriosam culpa molestiae commodi id. Aperiam facere natus deserunt est asperiores. Sequi modi velit asperiores voluptatem.'
                    ended_at: null
                    institution_id: 17
                    institution_name: 'Yasmine Walter'
      tags:
        - Trender
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: ''
                  example: corporis
                category_ids:
                  type: object
                  description: ''
                  example: null
                  properties: []
                cities:
                  type: object
                  description: ''
                  example: null
                  properties: []
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The details field must be an array.'
                  errors:
                    details:
                      - 'The details field must be an array.'
                properties:
                  message:
                    type: string
                    example: 'The details field must be an array.'
                  errors:
                    type: object
                    properties:
                      details:
                        type: array
                        example:
                          - 'The details field must be an array.'
                        items:
                          type: string
      tags:
        - Trender
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: quia
                description:
                  type: string
                  description: ''
                  example: 'Voluptatem soluta nam magni sed atque id.'
                details:
                  type: object.
                  description: ''
                  example: "[\n {\n    \"type\": \"text\",\n    \"data\": {\n     \"validator\": {\n \"required\": true,\n\"error_message\": \"Invalid parameters\"\n}\n}\n }\n]"
              required:
                - title
                - description
      security: []
  '/api/trender/{id}':
    get:
      summary: ''
      operationId: getApiTrenderId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 25
                    title: 'Eum officia eum.'
                    description: 'Porro doloremque molestiae culpa temporibus perferendis minima. Qui non nulla dolorem laudantium.'
                    created_at: '2023-09-17T08:12:58.000000Z'
                    ended_at: '2023-09-17 09:25:57'
                    offers_count: 3
                    best_offer_from: 'Barry Barton'
                    offers:
                      -
                        id: 11
                        trender_name: 'Eum officia eum.'
                        for: 'Dr. Delfina Lesch'
                        work_on_it: '2023-09-17T09:17:03.000000Z'
                        work_ended_it: '2023-09-17 09:25:57'
                      -
                        id: 12
                        trender_name: 'Eum officia eum.'
                        for: 'Dr. Delfina Lesch'
                        work_on_it: '2023-09-17T09:17:03.000000Z'
                        work_ended_it: '2023-09-17 09:25:57'
                      -
                        id: 13
                        trender_name: 'Eum officia eum.'
                        for: 'Dr. Delfina Lesch'
                        work_on_it: '2023-09-17T09:17:03.000000Z'
                        work_ended_it: '2023-09-17 09:25:57'
                    trender_details:
                      -
                        id: 10
                        type: quis
                        question: est
                        description: 'Natus sunt enim beatae quo. Et nisi est dolorum nihil et similique facilis nihil. Explicabo incidunt ut excepturi.'
                        data: molestias
                        tender_id: 25
                        created_at: '2023-09-17T08:12:58.000000Z'
                        updated_at: '2023-09-17T08:12:58.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 25
                      title:
                        type: string
                        example: 'Eum officia eum.'
                      description:
                        type: string
                        example: 'Porro doloremque molestiae culpa temporibus perferendis minima. Qui non nulla dolorem laudantium.'
                      created_at:
                        type: string
                        example: '2023-09-17T08:12:58.000000Z'
                      ended_at:
                        type: string
                        example: '2023-09-17 09:25:57'
                      offers_count:
                        type: integer
                        example: 3
                      best_offer_from:
                        type: string
                        example: 'Barry Barton'
                      offers:
                        type: array
                        example:
                          -
                            id: 11
                            trender_name: 'Eum officia eum.'
                            for: 'Dr. Delfina Lesch'
                            work_on_it: '2023-09-17T09:17:03.000000Z'
                            work_ended_it: '2023-09-17 09:25:57'
                          -
                            id: 12
                            trender_name: 'Eum officia eum.'
                            for: 'Dr. Delfina Lesch'
                            work_on_it: '2023-09-17T09:17:03.000000Z'
                            work_ended_it: '2023-09-17 09:25:57'
                          -
                            id: 13
                            trender_name: 'Eum officia eum.'
                            for: 'Dr. Delfina Lesch'
                            work_on_it: '2023-09-17T09:17:03.000000Z'
                            work_ended_it: '2023-09-17 09:25:57'
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 11
                            trender_name:
                              type: string
                              example: 'Eum officia eum.'
                            for:
                              type: string
                              example: 'Dr. Delfina Lesch'
                            work_on_it:
                              type: string
                              example: '2023-09-17T09:17:03.000000Z'
                            work_ended_it:
                              type: string
                              example: '2023-09-17 09:25:57'
                      trender_details:
                        type: array
                        example:
                          -
                            id: 10
                            type: quis
                            question: est
                            description: 'Natus sunt enim beatae quo. Et nisi est dolorum nihil et similique facilis nihil. Explicabo incidunt ut excepturi.'
                            data: molestias
                            tender_id: 25
                            created_at: '2023-09-17T08:12:58.000000Z'
                            updated_at: '2023-09-17T08:12:58.000000Z'
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 10
                            type:
                              type: string
                              example: quis
                            question:
                              type: string
                              example: est
                            description:
                              type: string
                              example: 'Natus sunt enim beatae quo. Et nisi est dolorum nihil et similique facilis nihil. Explicabo incidunt ut excepturi.'
                            data:
                              type: string
                              example: molestias
                            tender_id:
                              type: integer
                              example: 25
                            created_at:
                              type: string
                              example: '2023-09-17T08:12:58.000000Z'
                            updated_at:
                              type: string
                              example: '2023-09-17T08:12:58.000000Z'
      tags:
        - Trender
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Trender
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Trender
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the trender.'
        example: 1
        required: true
        schema:
          type: integer
  /api/mine-trender:
    get:
      summary: ''
      operationId: getApiMineTrender
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 25
                      title: 'Eum officia eum.'
                      description: 'Porro doloremque molestiae culpa temporibus perferendis minima. Qui non nulla dolorem laudantium.'
                      created_at: '2023-09-17T08:12:58.000000Z'
                      ended_at: null
                      offers_count: 3
                      best_offer_from:
                        id: 11
                        tender_id: 25
                        company_id: 20
                        is_draft: 0
                        created_at: '2023-09-17T09:17:03.000000Z'
                        updated_at: '2023-09-17T09:17:03.000000Z'
                      offers:
                        -
                          id: 11
                          trender_name: 'Eum officia eum.'
                          for: 'Dr. Delfina Lesch'
                          work_on_it: '2023-09-17T09:17:03.000000Z'
                          work_ended_it: null
                        -
                          id: 12
                          trender_name: 'Eum officia eum.'
                          for: 'Dr. Delfina Lesch'
                          work_on_it: '2023-09-17T09:17:03.000000Z'
                          work_ended_it: null
                        -
                          id: 13
                          trender_name: 'Eum officia eum.'
                          for: 'Dr. Delfina Lesch'
                          work_on_it: '2023-09-17T09:17:03.000000Z'
                          work_ended_it: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 25
                        title: 'Eum officia eum.'
                        description: 'Porro doloremque molestiae culpa temporibus perferendis minima. Qui non nulla dolorem laudantium.'
                        created_at: '2023-09-17T08:12:58.000000Z'
                        ended_at: null
                        offers_count: 3
                        best_offer_from:
                          id: 11
                          tender_id: 25
                          company_id: 20
                          is_draft: 0
                          created_at: '2023-09-17T09:17:03.000000Z'
                          updated_at: '2023-09-17T09:17:03.000000Z'
                        offers:
                          -
                            id: 11
                            trender_name: 'Eum officia eum.'
                            for: 'Dr. Delfina Lesch'
                            work_on_it: '2023-09-17T09:17:03.000000Z'
                            work_ended_it: null
                          -
                            id: 12
                            trender_name: 'Eum officia eum.'
                            for: 'Dr. Delfina Lesch'
                            work_on_it: '2023-09-17T09:17:03.000000Z'
                            work_ended_it: null
                          -
                            id: 13
                            trender_name: 'Eum officia eum.'
                            for: 'Dr. Delfina Lesch'
                            work_on_it: '2023-09-17T09:17:03.000000Z'
                            work_ended_it: null
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 25
                        title:
                          type: string
                          example: 'Eum officia eum.'
                        description:
                          type: string
                          example: 'Porro doloremque molestiae culpa temporibus perferendis minima. Qui non nulla dolorem laudantium.'
                        created_at:
                          type: string
                          example: '2023-09-17T08:12:58.000000Z'
                        ended_at:
                          type: string
                          example: null
                        offers_count:
                          type: integer
                          example: 3
                        best_offer_from:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 11
                            tender_id:
                              type: integer
                              example: 25
                            company_id:
                              type: integer
                              example: 20
                            is_draft:
                              type: integer
                              example: 0
                            created_at:
                              type: string
                              example: '2023-09-17T09:17:03.000000Z'
                            updated_at:
                              type: string
                              example: '2023-09-17T09:17:03.000000Z'
                        offers:
                          type: array
                          example:
                            -
                              id: 11
                              trender_name: 'Eum officia eum.'
                              for: 'Dr. Delfina Lesch'
                              work_on_it: '2023-09-17T09:17:03.000000Z'
                              work_ended_it: null
                            -
                              id: 12
                              trender_name: 'Eum officia eum.'
                              for: 'Dr. Delfina Lesch'
                              work_on_it: '2023-09-17T09:17:03.000000Z'
                              work_ended_it: null
                            -
                              id: 13
                              trender_name: 'Eum officia eum.'
                              for: 'Dr. Delfina Lesch'
                              work_on_it: '2023-09-17T09:17:03.000000Z'
                              work_ended_it: null
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 11
                              trender_name:
                                type: string
                                example: 'Eum officia eum.'
                              for:
                                type: string
                                example: 'Dr. Delfina Lesch'
                              work_on_it:
                                type: string
                                example: '2023-09-17T09:17:03.000000Z'
                              work_ended_it:
                                type: string
                                example: null
      tags:
        - Trender
      security: []
  '/api/trender/{tender_id}/close':
    post:
      summary: ''
      operationId: postApiTrenderTender_idClose
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Trender
      security: []
    parameters:
      -
        in: path
        name: tender_id
        description: 'The ID of the tender.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Authentication
    description: ''
  -
    name: Category
    description: ''
  -
    name: Offer
    description: ''
  -
    name: Trender
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
